# Generated by Django 4.1.5 on 2023-01-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.CharField(max_length=255, verbose_name='full link')),
                ('short_link', models.CharField(max_length=255, verbose_name='shortened link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='datetime of creation')),
                ('delete_at', models.DateTimeField(verbose_name='datetime to delete')),
                ('redirect_count', models.IntegerField(default=0, verbose_name='count of redirects')),
                ('redirect_limit', models.IntegerField(verbose_name='redirect limit')),
                ('active', models.BooleanField(default=True, verbose_name='activity')),
            ],
            options={
                'db_table': 'redirection',
            },
        ),
    ]
